[package]
name = "challenges"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[[bin]]
name = "factorial"
path = "./src/bin/factorial.rs"

[[bin]]
name = "serialization_json"
path = "./src/bin/serialization_json.rs"
